### ISSUE TITLE
MQTT client returns a buffer instead of a string

### ISSUE THREAD

**Issue by tomchambers2** [MichielvdVelde/Adhesion#1]
When sending a message, it comes back from mqttClient as a buffer like <Buffer 62 6c 61 68> rather than 'blah'.

I've added this to my index.js:

```
var payload = { 'action': 'message', 'topic': topic, 'message': message.toString('utf8') };
```

Not sure if that would be suitable in all cases.

**Comment by MichielvdVelde** [comment]
Better late than never, they say. I don't maintain this code anymore, since I reworked it a while ago and is now available as [adhesion-server](http://github.com/MichielvdVelde/adhesion-server) or [adhesion-proxy](http://github.com/MichielvdVelde/adhesion-proxy). If I remember correctly I fixed a similar problem there..
